apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payments-api-service
  annotations:
    github.com/project-slug: konrness/harness-software-catalog
    harness.io/cd-serviceId: paymentsapiservice
  links:
    - url: https://payments-api.example.com
      title: Payments API Endpoint
  datadogServiceHealth: 100
spec:
  type: service
  lifecycle: production
  owner: Sales
  system: payments
